FROM python:3.5

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir metapy pytoml

WORKDIR /home/python/app

# infinite loop
# ENTRYPOINT ["tail", "-f", "/dev/null"]

CMD ["python", "example.py"]